#! /bin/bash
#
# Keep track of the status of VPN.  This script is called from the Windows Task
# Scheduler with option `--up` when a new connection is detected and the VPN is
# up and with `--down` when a connection failure is detected and the VPN is
# down.  Note that connections unrelated to the VPN can come and go, so this
# script can be called spuriously (e.g., if a new connection is detected and
# the vpn is already connected).  For that reason, this script will ignore
# `--up` and `--down` if they are duplicates of the current state.
#
# This script will also query the state of the VPN (with no argument or with
# the `--stat` argument) and can dump appropriate proxy environment variable
# definitions (if called with the `--env` argument).
#
# Add commands to the `onVpnUp` and `onVpnDown` functions, below, to cause
# those commands to run on a vpn state change.

function onVpnUp
{
    cp /etc/apt/proxy.conf.bbVPN /etc/apt/apt.conf.d/proxy.conf
    cp ~/.ssh/config.bbVPN ~/.ssh/config
    cp ~/.wgetrc.bbVPN ~/.wgetrc
    cat ~/.gitconfig.common ~/.gitconfig.bbVPN > ~/.gitconfig
    # ~/bin/update-ssh-names  # Auth hangs when launched from scheduler
}

function onVpnDown
{
    cp /dev/null /etc/apt/apt.conf.d/proxy.conf
    cp ~/.ssh/config.pablo ~/.ssh/config
    cp ~/.wgetrc.pablo ~/.wgetrc
    cp ~/.gitconfig.common ~/.gitconfig
}

function usage
{
    cat <<EOF >&2
Usage:
  Silently returns success if connected          : bbvpn [ --stat ]
  Also echo "up" or "down" status to stdout      : bbvpn --echo
  Register vpn as being connected                : bbvpn --up
  Register vpn as being disconnected             : bbvpn --down
  Print proxy environment variable settings      : bbvpn --env
  Detect vpn connection, but don't update status : bbvpn --detect
  Detect and update vpn connection status        : bbvpn --update
EOF

    exit 2
}

# The status file should always exist. It is set to writable if the VPN is in a
# connected (up) state and is otherwise read-only.
statusfile=/etc/bbVPN/status.txt

# Set vpn status to UP
function setStatusUp
{
    chmod a+w $statusfile
}

# Set vpn status to DOWN
function setStatusDown
{
    chmod a-w $statusfile
}

# Return last-known status of bbvpn.  Returns success if UP, failure if DOWN.
function lastStatus
{
    if [ -w $statusfile ]; then
        return 0
    else
        return 1
    fi
}

# Return success if the bb Vpn is connected, otherwise failure. Does not change
# the known status.
function detectVpn
{
    # If can connect through BB proxy, then succeed.
    nc -d -w 1 -X connect -x "proxy.bloomberg.com:81" -z wg21.link 80 > /dev/null 2>&1 || return 1
    return 0
}

# Detect whether the bb Vpn is connected and update the known status.
function update
{
    if detectVpn; then
        if ! lastStatus; then
            setStatusUp
            onVpnUp
        fi
        return 0
    else
        if lastStatus; then
            setStatusDown
            onVpnDown
        fi
        return 1
    fi
}

function dumpenv
{
    if [ -w $statusfile ]; then
        cat <<EOF
export http_proxy=http://devproxy.bloomberg.com:82
export https_proxy=http://devproxy.bloomberg.com:82
export no_proxy="*.bloomberg.com,*.bloomberg.net"
EOF
    else
        cat <<EOF
unset http_proxy
unset https_proxy
export no_proxy="*"
EOF
    fi
}

if [ ! -f $statusfile ]; then
    echo "This file is writable if VPN is connected, else read-only." > $statusfile
    chmod a+r,a-w $statusfile
fi

case "${1:---stat}" in
    --help) usage ;;
    --stat) lastStatus || exit 1 ;;
    --echo) if lastStatus; then
                echo up
                exit 0
            else
                echo down
                exit 1
            fi
            ;;
    --up)   if ! lastStatus; then
                setStatusUp
                onVpnUp
            fi
            ;;
    --down) if lastStatus; then
                setStatusDown
                onVpnDown
            fi
            ;;
    --detect) detectVpn || exit 1 ;;
    --update) update    || exit 1 ;;
    --env)  dumpenv ;;
    *)      usage   ;;
esac

exit 0
