#! /bin/bash

# Usage: mydocker [name=value]... <command> [ args... ]
#
# This wrapper around docker attempts to make the container environment as
# similar as possible to the host environment by performing the following
# magic:
#
# 1. Mounts the `$HOME` directory in docker using the exact same path.
# 2. If `mydocker` is run in (a subdirectory of) `$HOME`, runs the docker
#    instance in the same subdirectory.
# 3. If the `command` argument is found in `$HOME/bin` on the host, runs the
#    identical command in the container.
# 4. If this script is run from an interactive shell, runs docker in
#    interactive mode.
# 5. Runs the container with the same uid and guid as the host.
# 6. If one or more `name=value` pairs are specified, the corresponding
#    environment variable are set before running the command.
#
# This script does not attempt to copy over environment variables, preferring
# to let the executed script set things such as the build environment.

image_name=bde-docker-dev
container_name=dev
# image_name=bdebuildbase

# If current directory is a subdirectory of $HOME, then set docker instance
# to current directory; otherwise, use the default "/workspace"
wd="/workspace"
if [ "${PWD#$HOME}" != "$PWD" ]; then
   wd="$PWD"
fi

# $homebin is the directory holding favorite custom scripts
homebin="$HOME/bin"

# Strip environment variables from front
env_list=()
while [ $# != 0 ]; do
    if echo "$1" | grep "^[a-zA-Z_][a-zA-Z_0-9]*=" > /dev/null; then
        env_list+=("$1")
        shift
    else
        break
    fi
done

# If `command` is found in `$homebin` folder, use full path to command within
# the container; otherwise, let the container figure out the path on its own.
cmd=$(which "$1")  # Get full path to command (if found outside of container)
if [ "${cmd#$homebin}" = "$cmd" ]; then
    # Command was not found in $homebin, set `$cmd` to argument value and let
    # the container figure out the path on its own.
    cmd="$1"
fi
shift

# If run from an interactive shell, set docker to interactive mode
if tty -s; then
    interactive="-it"
else
    interactive=""
fi

# Check that docker image exists
if ! docker images | grep "^$image_name " > /dev/null; then
    echo >&2 "Docker image doesn't exist. Run 'bde_docker build'."
    exit 1
fi

# Check container status
container_ps=$(docker ps -a | grep " $container_name\$")
case $container_ps in
    "")       container_status=none     ;;
    *\ Up\ *) container_status=running;;
    *)        container_status=stopped  ;;
esac

if [ $container_status == none ]; then
    # Docker container does not exist, create it from the docker image
    (cd ~/bbcm/bde &&
         MACHINE=$(uname -m) docker compose -f ~/.bde-docker/compose.yaml create)
#    docker run -d -t --name $container_name -v "$HOME:$HOME" -v "$HOME/bbcm/bde-tools:/bde-tools" -u $(id -u):$(id -g) -w "$HOME" $image_name
fi

# Start docker image (in case it's not running), then execute $cmd
docker start $container_name > /dev/null
docker exec $interactive -w $wd $container_name env "${env_list[@]}" "$cmd" "$@"
if [ $container_status != running ]; then
    # Container was not running when we started.
    # Return container to a stopped state when done.
    docker stop $container_name > /dev/null &
fi
